# Generated by Django 4.1 on 2022-10-10 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acc_income_expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_date', models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2022, 10, 10, 14, 20, 57, 317694))),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=30)),
                ('category', models.CharField(db_column='CATEGORY', max_length=30)),
                ('amount_in', models.DecimalField(blank=True, db_column='AMOUNT_IN', decimal_places=2, max_digits=20, null=True)),
                ('amount_out', models.DecimalField(blank=True, db_column='AMOUNT_OUT', decimal_places=2, max_digits=20, null=True)),
                ('overall_balance', models.DecimalField(db_column='OVERALL_BALANCE', decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'ACC_INC_EXP',
            },
        ),
    ]
