# Generated by Django 4.1 on 2022-10-10 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_income_expense',
            name='account_type',
            field=models.CharField(db_column='ACCOUNT_TYPE', default='Bank BRI', max_length=30),
        ),
        migrations.AlterField(
            model_name='acc_income_expense',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2022, 10, 10, 14, 22, 57, 990247)),
        ),
    ]
