# Generated by Django 4.1 on 2022-11-17 04:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bll_trx_billing_invoice_status'),
        ('account', '0003_acc_income_expense_bll_mst_item_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='acc_investment_deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2022, 11, 17, 11, 35, 1, 425696))),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=30)),
                ('amount', models.DecimalField(blank=True, db_column='AMOUNT', decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'ACC_INVESTMENT_DEPOSIT',
            },
        ),
        migrations.CreateModel(
            name='acc_investment_fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2022, 11, 17, 11, 35, 1, 425696))),
                ('fund_code', models.CharField(db_column='FUND_NAME', max_length=30)),
                ('average_nav', models.DecimalField(blank=True, db_column='AVERAGE_NAV', decimal_places=2, max_digits=20, null=True)),
                ('current_nav', models.DecimalField(blank=True, db_column='CURRENT_NAV', decimal_places=2, max_digits=20, null=True)),
                ('unit', models.DecimalField(blank=True, db_column='UNIT', decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'ACC_INVESTMENT_FUND',
            },
        ),
        migrations.CreateModel(
            name='acc_investment_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2022, 11, 17, 11, 35, 1, 425696))),
                ('stock_code', models.CharField(db_column='STOCKS', max_length=30)),
                ('average', models.DecimalField(blank=True, db_column='AVERAGE_PRICE', decimal_places=2, max_digits=20, null=True)),
                ('der_annual', models.DecimalField(blank=True, db_column='DER_ANNUAL', decimal_places=2, max_digits=20, null=True)),
                ('bv_5', models.DecimalField(blank=True, db_column='BV_5', decimal_places=2, max_digits=20, null=True)),
                ('bv_annual', models.DecimalField(blank=True, db_column='BV_ANNUAL', decimal_places=2, max_digits=20, null=True)),
                ('dividend', models.DecimalField(blank=True, db_column='DIVIDEND', decimal_places=2, max_digits=20, null=True)),
                ('lot', models.IntegerField(db_column='LOT')),
            ],
            options={
                'db_table': 'ACC_INVESTMENT_STOCK',
            },
        ),
        migrations.RemoveField(
            model_name='acc_income_expense',
            name='category',
        ),
        migrations.AlterField(
            model_name='acc_income_expense',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2022, 11, 17, 11, 35, 1, 424704)),
        ),
        migrations.CreateModel(
            name='acc_ar_debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_date', models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2022, 11, 17, 11, 35, 1, 425696))),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=30)),
                ('amount', models.DecimalField(blank=True, db_column='AMOUNT', decimal_places=2, max_digits=20, null=True)),
                ('account_status', models.IntegerField(db_column='ACCOUNT_STATUS')),
                ('account_type', models.CharField(db_column='ACCOUNT_TYPE', max_length=30)),
                ('bll_mst_item_id', models.ForeignKey(db_column='BLL_MST_BILL_ITEM_ID', default=1, on_delete=django.db.models.deletion.RESTRICT, to='billing.bll_mst_bill_item')),
            ],
            options={
                'db_table': 'ACC_AR_DEBT',
            },
        ),
    ]
