# Generated by Django 4.1 on 2022-12-01 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_acc_investment_deposit_acc_investment_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_ar_debt',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2022, 12, 1, 16, 1, 41, 957061)),
        ),
        migrations.AlterField(
            model_name='acc_ar_debt',
            name='account_status',
            field=models.CharField(db_column='ACCOUNT_STATUS', max_length=30),
        ),
        migrations.AlterField(
            model_name='acc_income_expense',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2022, 12, 1, 16, 1, 41, 957061)),
        ),
        migrations.AlterField(
            model_name='acc_investment_deposit',
            name='date_created',
            field=models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2022, 12, 1, 16, 1, 41, 958061)),
        ),
        migrations.AlterField(
            model_name='acc_investment_fund',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2022, 12, 1, 16, 1, 41, 958061)),
        ),
        migrations.AlterField(
            model_name='acc_investment_stock',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2022, 12, 1, 16, 1, 41, 958061)),
        ),
    ]
