# Generated by Django 4.1 on 2022-12-01 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_acc_ar_debt_account_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_ar_debt',
            name='valid_status',
            field=models.CharField(db_column='VALID_STATUS', default='VALID', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acc_ar_debt',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2022, 12, 1, 16, 5, 17, 727849)),
        ),
        migrations.AlterField(
            model_name='acc_income_expense',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2022, 12, 1, 16, 5, 17, 727849)),
        ),
        migrations.AlterField(
            model_name='acc_investment_deposit',
            name='date_created',
            field=models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2022, 12, 1, 16, 5, 17, 728847)),
        ),
        migrations.AlterField(
            model_name='acc_investment_fund',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2022, 12, 1, 16, 5, 17, 728847)),
        ),
        migrations.AlterField(
            model_name='acc_investment_stock',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2022, 12, 1, 16, 5, 17, 727849)),
        ),
    ]
