# Generated by Django 4.1 on 2022-12-02 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_acc_ar_debt_valid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_ar_debt',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2022, 12, 2, 15, 25, 23, 585296)),
        ),
        migrations.AlterField(
            model_name='acc_income_expense',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2022, 12, 2, 15, 25, 23, 585296)),
        ),
        migrations.AlterField(
            model_name='acc_investment_deposit',
            name='date_created',
            field=models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2022, 12, 2, 15, 25, 23, 586298)),
        ),
        migrations.AlterField(
            model_name='acc_investment_fund',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2022, 12, 2, 15, 25, 23, 586298)),
        ),
        migrations.AlterField(
            model_name='acc_investment_stock',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2022, 12, 2, 15, 25, 23, 585296)),
        ),
    ]
