# Generated by Django 4.1 on 2023-01-18 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_acc_ar_debt_account_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_income_expense',
            name='remarks',
            field=models.CharField(db_column='REMARKS', default='NULL', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acc_ar_debt',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2023, 1, 18, 21, 12, 25, 249326)),
        ),
        migrations.AlterField(
            model_name='acc_income_expense',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2023, 1, 18, 21, 12, 25, 249326)),
        ),
        migrations.AlterField(
            model_name='acc_investment_deposit',
            name='date_created',
            field=models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2023, 1, 18, 21, 12, 25, 250326)),
        ),
        migrations.AlterField(
            model_name='acc_investment_fund',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 1, 18, 21, 12, 25, 250326)),
        ),
        migrations.AlterField(
            model_name='acc_investment_stock',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 1, 18, 21, 12, 25, 249326)),
        ),
    ]
