# Generated by Django 4.1 on 2023-05-30 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_acc_investment_stock_last_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='acc_saving_goal_tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2023, 5, 30, 10, 40, 18, 986015))),
                ('goal_name', models.CharField(db_column='GOAL_NAME', max_length=30)),
                ('final_saving_goal', models.DecimalField(db_column='FINAL_SAVING_GOAL', decimal_places=4, max_digits=20)),
                ('inflation_rate', models.DecimalField(db_column='INFLATION_RATE', decimal_places=4, max_digits=20)),
                ('curr_value', models.IntegerField(db_column='CURRENT_VALUE')),
                ('period_in_year', models.IntegerField(db_column='PERIOD_IN_YEAR')),
                ('fund_id', models.IntegerField(db_column='FUND_ID')),
            ],
            options={
                'db_table': 'ACC_SAVING_GOAL_TRACKER',
            },
        ),
        migrations.AlterField(
            model_name='acc_ar_debt',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2023, 5, 30, 10, 40, 18, 985015)),
        ),
        migrations.AlterField(
            model_name='acc_income_expense',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2023, 5, 30, 10, 40, 18, 985015)),
        ),
        migrations.AlterField(
            model_name='acc_investment_deposit',
            name='date_created',
            field=models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2023, 5, 30, 10, 40, 18, 986015)),
        ),
        migrations.AlterField(
            model_name='acc_investment_fund',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 5, 30, 10, 40, 18, 986015)),
        ),
        migrations.AlterField(
            model_name='acc_investment_stock',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 5, 30, 10, 40, 18, 985015)),
        ),
        migrations.AlterField(
            model_name='acc_investment_stock',
            name='last_price',
            field=models.IntegerField(blank=True, db_column='LAST_PRICE', default='', null=True),
        ),
        migrations.AlterField(
            model_name='acc_investment_stock',
            name='last_price_date',
            field=models.DateTimeField(db_column='LAST__PRICE_UPDATE_DATE', default=datetime.datetime(2023, 5, 30, 10, 40, 18, 985015)),
        ),
    ]
