# Generated by Django 4.1 on 2023-05-31 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_acc_saving_goal_tracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_investment_fund',
            name='exp_return',
            field=models.DecimalField(blank=True, db_column='EXPECTED_RETURN', decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='acc_ar_debt',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2023, 6, 1, 2, 57, 30, 90260)),
        ),
        migrations.AlterField(
            model_name='acc_income_expense',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2023, 6, 1, 2, 57, 30, 89259)),
        ),
        migrations.AlterField(
            model_name='acc_investment_deposit',
            name='date_created',
            field=models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2023, 6, 1, 2, 57, 30, 90260)),
        ),
        migrations.AlterField(
            model_name='acc_investment_fund',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 6, 1, 2, 57, 30, 90260)),
        ),
        migrations.AlterField(
            model_name='acc_investment_stock',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 6, 1, 2, 57, 30, 90260)),
        ),
        migrations.AlterField(
            model_name='acc_investment_stock',
            name='last_price_date',
            field=models.DateTimeField(db_column='LAST__PRICE_UPDATE_DATE', default=datetime.datetime(2023, 6, 1, 2, 57, 30, 90260)),
        ),
        migrations.AlterField(
            model_name='acc_saving_goal_tracker',
            name='date_created',
            field=models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2023, 6, 1, 2, 57, 30, 91261)),
        ),
    ]
