# Generated by Django 4.1 on 2023-07-23 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_acc_investment_fund_exp_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_ar_debt',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2023, 7, 23, 22, 22, 22, 778620)),
        ),
        migrations.AlterField(
            model_name='acc_income_expense',
            name='account_date',
            field=models.DateTimeField(db_column='ACCOUNT_DATE', default=datetime.datetime(2023, 7, 23, 22, 22, 22, 778620)),
        ),
        migrations.AlterField(
            model_name='acc_investment_deposit',
            name='date_created',
            field=models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2023, 7, 23, 22, 22, 22, 794322)),
        ),
        migrations.AlterField(
            model_name='acc_investment_fund',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 7, 23, 22, 22, 22, 778620)),
        ),
        migrations.AlterField(
            model_name='acc_investment_stock',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 7, 23, 22, 22, 22, 778620)),
        ),
        migrations.AlterField(
            model_name='acc_investment_stock',
            name='last_price_date',
            field=models.DateTimeField(db_column='LAST__PRICE_UPDATE_DATE', default=datetime.datetime(2023, 7, 23, 22, 22, 22, 778620)),
        ),
        migrations.AlterField(
            model_name='acc_saving_goal_tracker',
            name='date_created',
            field=models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2023, 7, 23, 22, 22, 22, 794322)),
        ),
    ]
