# Generated by Django 4.1 on 2022-10-08 16:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_alter_std_trx_course_amount_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bll_mst_bill_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(db_column='ITEM_NAME', max_length=30)),
                ('debet_credit', models.IntegerField(db_column='DEBET_CREDIT')),
                ('validstatus', models.IntegerField(blank=True, db_column='VALID_STATUS', default=1, null=True)),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', default=datetime.date.today)),
                ('created_by', models.CharField(db_column='CREATED_BY', max_length=30)),
            ],
            options={
                'db_table': 'BLL_MST_BILL_ITEM',
            },
        ),
        migrations.CreateModel(
            name='bll_trx_billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(db_column='INVOICE_DATE', default=datetime.date.today)),
                ('total_amount', models.DecimalField(db_column='TOTAL_AMOUNT', decimal_places=2, max_digits=12)),
                ('remarks', models.CharField(db_column='REMARKS', max_length=30)),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', default=django.utils.timezone.now)),
                ('created_by', models.CharField(db_column='CREATED_BY', max_length=30)),
                ('date_modified', models.DateField(blank=True, db_column='DATE_MODIFIED', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', max_length=30, null=True)),
                ('tobe_paid', models.DecimalField(db_column='TOBE_PAID', decimal_places=2, max_digits=12)),
                ('month', models.IntegerField(db_column='MONTH')),
                ('year', models.IntegerField(db_column='YEAR')),
                ('periode', models.IntegerField(db_column='PERIODE')),
                ('std_trx_id', models.ForeignKey(db_column='STD_TRX_ID', on_delete=django.db.models.deletion.RESTRICT, to='student.std_trx')),
            ],
            options={
                'db_table': 'BLL_TRX_BILLING',
            },
        ),
        migrations.CreateModel(
            name='bll_trx_bill_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=30)),
                ('value', models.IntegerField(db_column='VALUE')),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', default=datetime.date.today)),
                ('created_by', models.CharField(db_column='CREATED_BY', max_length=30)),
                ('date_modified', models.DateField(blank=True, db_column='DATE_MODIFIED', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', max_length=30, null=True)),
                ('bll_mst_id', models.ForeignKey(db_column='BLL_MST_BILL_ITEM_ID', on_delete=django.db.models.deletion.RESTRICT, to='billing.bll_mst_bill_item')),
                ('btb_id', models.ForeignKey(db_column='BLL_TRX_BILLING_ID', on_delete=django.db.models.deletion.RESTRICT, to='billing.bll_trx_billing')),
                ('std_trx_id', models.ForeignKey(db_column='STD_TRX_ID', on_delete=django.db.models.deletion.RESTRICT, to='student.std_trx')),
            ],
            options={
                'db_table': 'BLL_TRX_BILL_ITEM',
            },
        ),
    ]
