# Generated by Django 4.1 on 2022-10-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bll_trx_bill_item_std_trx_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bll_trx_billing',
            name='invoice_status',
            field=models.IntegerField(db_column='INVOICE_STATUS', default=0),
        ),
    ]
