# Generated by Django 4.1 on 2023-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bll_trx_billing_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bll_mst_bill_item',
            name='category',
            field=models.CharField(db_column='CATEGORY', default='MONTHLY-EXPENSE', max_length=30),
        ),
    ]
