# Generated by Django 4.1 on 2022-10-08 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prd_mst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(db_column='COURSE_NAME', max_length=30)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=30)),
                ('validuntil', models.DateField(blank=True, db_column='VALID_UNTIL', null=True)),
                ('remarks', models.CharField(db_column='REMARKS', max_length=30)),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', default=datetime.date.today)),
                ('created_by', models.CharField(db_column='CREATED_BY', max_length=30)),
                ('date_modified', models.DateField(blank=True, db_column='DATE_MODIFIED', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', max_length=30, null=True)),
            ],
            options={
                'db_table': 'PRD_MST',
            },
        ),
    ]
