# Generated by Django 4.1 on 2022-10-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prd_mst',
            name='remarks',
            field=models.CharField(blank=True, db_column='REMARKS', max_length=30, null=True),
        ),
    ]
