# Generated by Django 4.1 on 2023-09-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_prd_mst_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prd_mst',
            name='description',
            field=models.CharField(db_column='DESCRIPTION', max_length=150),
        ),
    ]
