# Generated by Django 4.1 on 2022-10-06 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_mst_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulename', models.CharField(db_column='MODULENAME', max_length=30)),
                ('pagename', models.CharField(db_column='PAGENAME', max_length=30)),
                ('created_by', models.CharField(db_column='CREATED_BY', max_length=30)),
                ('date_created', models.DateField(db_column='DATE_CREATED', default=datetime.date.today)),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', max_length=30)),
                ('date_modified', models.DateField(blank=True, db_column='DATE_MODIFIED')),
                ('validstatus', models.IntegerField(blank=True, db_column='VALIDSTATUS')),
                ('ordernumber', models.IntegerField(db_column='ORDERNUMBER')),
                ('levelnumber', models.IntegerField(blank=True, db_column='LEVELNUMBER')),
                ('moduleurl', models.CharField(blank=True, db_column='MODULEURL', max_length=30)),
                ('moduleicon', models.CharField(blank=True, db_column='MODULEICON', max_length=30)),
                ('moduleclass', models.CharField(blank=True, db_column='MODULECLASS', max_length=30)),
                ('application', models.CharField(db_column='APPLICATION', max_length=30)),
            ],
            options={
                'db_table': 'ADM_MST_MODULE',
            },
        ),
    ]
