# Generated by Django 4.1 on 2022-10-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_mst_module',
            name='date_modified',
            field=models.DateField(blank=True, db_column='DATE_MODIFIED', null=True),
        ),
        migrations.AlterField(
            model_name='admin_mst_module',
            name='levelnumber',
            field=models.IntegerField(blank=True, db_column='LEVELNUMBER', null=True),
        ),
        migrations.AlterField(
            model_name='admin_mst_module',
            name='modified_by',
            field=models.CharField(blank=True, db_column='MODIFIED_BY', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admin_mst_module',
            name='moduleclass',
            field=models.CharField(blank=True, db_column='MODULECLASS', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admin_mst_module',
            name='moduleicon',
            field=models.CharField(blank=True, db_column='MODULEICON', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admin_mst_module',
            name='moduleurl',
            field=models.CharField(blank=True, db_column='MODULEURL', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admin_mst_module',
            name='validstatus',
            field=models.IntegerField(blank=True, db_column='VALIDSTATUS', null=True),
        ),
    ]
