# Generated by Django 4.1 on 2022-10-06 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_admin_mst_module_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_mst_module',
            name='date_created',
            field=models.DateField(blank=True, db_column='DATE_CREATED', default=datetime.date.today),
        ),
    ]
