# Generated by Django 4.1 on 2022-10-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_admin_mst_module_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_mst_module',
            name='adm_mst_id',
            field=models.IntegerField(blank=True, db_column='ADM_MST_MODULE_ID', null=True),
        ),
    ]
