# Generated by Django 4.1 on 2022-10-08 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='std_mst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NAME', max_length=30)),
                ('phone', models.CharField(db_column='BOOKED_PHONE', max_length=30)),
                ('email', models.CharField(db_column='EMAIL', max_length=30)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=30, null=True)),
                ('validuntil', models.DateField(blank=True, db_column='VALID_UNTIL', null=True)),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', default=datetime.date.today)),
                ('created_by', models.CharField(db_column='CREATED_BY', max_length=30)),
                ('date_modified', models.DateField(blank=True, db_column='DATE_MODIFIED', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', max_length=30, null=True)),
                ('reason', models.CharField(blank=True, db_column='REASON_TERMINATE', max_length=30, null=True)),
            ],
            options={
                'db_table': 'STD_MST',
            },
        ),
    ]
