# Generated by Django 4.1 on 2022-10-08 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_std_trx'),
    ]

    operations = [
        migrations.CreateModel(
            name='std_trx_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(blank=True, db_column='DATETIME', default=datetime.date.today)),
                ('amount_hour', models.IntegerField(db_column='AMOUNT_HOUR')),
                ('validuntil', models.DateField(blank=True, db_column='VALID_UNTIL', null=True)),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', default=datetime.date.today)),
                ('created_by', models.CharField(db_column='CREATED_BY', max_length=30)),
                ('date_modified', models.DateField(blank=True, db_column='DATE_MODIFIED', null=True)),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', max_length=30, null=True)),
                ('std_trx_id', models.ForeignKey(db_column='STD_TRX_ID', on_delete=django.db.models.deletion.RESTRICT, to='student.std_trx')),
            ],
            options={
                'db_table': 'STD_TRX_COURSE',
            },
        ),
    ]
