# Generated by Django 4.1 on 2022-10-08 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_std_trx_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_trx_course',
            name='amount_hour',
            field=models.DecimalField(db_column='AMOUNT_HOUR', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='std_trx_course',
            name='date_created',
            field=models.DateField(blank=True, db_column='DATE_CREATED', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='std_trx_course',
            name='date_time',
            field=models.DateTimeField(blank=True, db_column='DATETIME', default=django.utils.timezone.now),
        ),
    ]
