# Generated by Django 4.1 on 2022-10-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_std_trx_course_amount_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_mst',
            name='gender',
            field=models.CharField(db_column='GENDER', default='M', max_length=1),
        ),
    ]
