# Generated by Django 4.1 on 2023-09-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_std_mst_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_mst',
            name='gender',
            field=models.CharField(db_column='GENDER', default='M', max_length=5),
        ),
    ]
