# Generated by Django 4.1 on 2023-09-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_std_mst_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_mst',
            name='reason',
            field=models.CharField(blank=True, db_column='REASON_TERMINATE', max_length=250, null=True),
        ),
    ]
