# Generated by Django 4.1 on 2023-07-23 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trd_mst_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 7, 23, 22, 24, 20, 492108))),
                ('stock_code', models.CharField(db_column='CODE', max_length=30)),
                ('valid_status', models.BooleanField(db_column='VALID_STATUS')),
            ],
            options={
                'db_table': 'TRD_MST_STOCK',
            },
        ),
        migrations.CreateModel(
            name='trd_trx_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2023, 7, 23, 22, 24, 20, 492108))),
                ('lot', models.IntegerField(db_column='LOT')),
                ('price', models.IntegerField(blank=True, db_column='PRICE', default='', null=True)),
                ('amount', models.FloatField(db_column='AMOUNT')),
                ('mst_id', models.ForeignKey(db_column='TRD_MST_STOCK', on_delete=django.db.models.deletion.RESTRICT, to='tradingstock.trd_mst_stock')),
            ],
            options={
                'db_table': 'TRD_TRX_STOCK',
            },
        ),
        migrations.CreateModel(
            name='trd_filtered_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 7, 23, 22, 24, 20, 492108))),
                ('last_price', models.IntegerField(blank=True, db_column='LAST_PRICE', default='', null=True)),
                ('ma_d_3', models.IntegerField(db_column='MA_D_3')),
                ('ma_d_5', models.IntegerField(db_column='MA_D_5')),
                ('ma_d_7', models.IntegerField(db_column='MA_D_7')),
                ('ma_d_10', models.IntegerField(db_column='MA_D_10')),
                ('ma_d_14', models.IntegerField(db_column='MA_D_14')),
                ('ma_d_18', models.IntegerField(db_column='MA_D_18')),
                ('ma_d_50', models.IntegerField(db_column='MA_D_50')),
                ('ma_d_100', models.IntegerField(db_column='MA_D_100')),
                ('ma_d_200', models.IntegerField(db_column='MA_D_200')),
                ('status', models.TextField(db_column='STATUS', max_length=30)),
                ('mst_id', models.ForeignKey(db_column='TRD_MST_STOCK', on_delete=django.db.models.deletion.RESTRICT, to='tradingstock.trd_mst_stock')),
            ],
            options={
                'db_table': 'TRD_FILTERED_STOCK',
            },
        ),
    ]
