# Generated by Django 4.1 on 2023-07-25 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingstock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trd_filtered_stock',
            name='last_open',
            field=models.IntegerField(blank=True, db_column='LAST_OPEN', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trd_filtered_stock',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 7, 25, 22, 39, 7, 659715)),
        ),
        migrations.AlterField(
            model_name='trd_filtered_stock',
            name='status',
            field=models.TextField(blank=True, db_column='STATUS', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trd_mst_stock',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 7, 25, 22, 39, 7, 659715)),
        ),
        migrations.AlterField(
            model_name='trd_trx_stock',
            name='date_created',
            field=models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2023, 7, 25, 22, 39, 7, 660712)),
        ),
    ]
