# Generated by Django 4.1 on 2023-07-25 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingstock', '0002_trd_filtered_stock_last_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trd_filtered_stock',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 7, 25, 22, 39, 45, 987479)),
        ),
        migrations.AlterField(
            model_name='trd_mst_stock',
            name='date_modified',
            field=models.DateTimeField(db_column='MODIFIED_DATE', default=datetime.datetime(2023, 7, 25, 22, 39, 45, 987479)),
        ),
        migrations.AlterField(
            model_name='trd_trx_stock',
            name='date_created',
            field=models.DateTimeField(db_column='CREATED_DATE', default=datetime.datetime(2023, 7, 25, 22, 39, 45, 987479)),
        ),
    ]
