# Generated by Django 4.1 on 2024-06-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingstock', '0014_alter_trd_filtered_stock_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trd_mst_stock',
            name='buy_price',
            field=models.IntegerField(blank=True, db_column='BUY_PRICE', default=0, null=True),
        ),
        migrations.AddField(
            model_name='trd_mst_stock',
            name='owned',
            field=models.BooleanField(db_column='OWNED', default=False),
        ),
    ]
