# Generated by Django 4.1 on 2024-06-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingstock', '0015_trd_mst_stock_buy_price_trd_mst_stock_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trd_mst_stock',
            name='stock_code',
            field=models.CharField(db_column='CODE', max_length=30, unique=True),
        ),
    ]
