# Generated by Django 4.2 on 2024-08-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tradingstock", "0016_alter_trd_mst_stock_stock_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="trd_trx_stock",
            name="is_last_transaction",
            field=models.BooleanField(db_column="IS_LAST_TRANSACTION", default=False),
        ),
    ]
