# Generated by Django 4.1 on 2023-11-28 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auto_mst_service_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(db_column='SERVICE_NAME', max_length=30)),
                ('repeating_kilometer', models.IntegerField(db_column='REPEATING_KILOMETER', default=0)),
                ('repeating_months', models.IntegerField(db_column='REPEATING_MONTHS', default=0)),
                ('service_type', models.CharField(db_column='SERVICE_TYPE', max_length=30)),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', default=datetime.datetime.now)),
                ('last_service_kilometer', models.IntegerField(db_column='LAST_SERVICE_KILOMETER')),
                ('last_service_date', models.DateField(db_column='LAST_SERVICE_DATE', default=datetime.datetime.now)),
                ('estimate_price', models.IntegerField(db_column='ESTIMATE_PRICE')),
            ],
            options={
                'db_table': 'AUTO_MST_SERVICE_ITEM',
            },
        ),
        migrations.CreateModel(
            name='auto_mst_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='VEHICLE_NAME', max_length=30)),
                ('year', models.IntegerField(db_column='YEAR')),
                ('current_kilometer', models.IntegerField(db_column='CURRENT_KILOMETER')),
                ('validstatus', models.IntegerField(blank=True, db_column='VALID_STATUS', default=1, null=True)),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'AUTO_MST_VEHICLE',
            },
        ),
        migrations.CreateModel(
            name='auto_service_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_kilometer', models.IntegerField(db_column='SERVICE_KILOMETER')),
                ('price', models.IntegerField(db_column='PRICE')),
                ('next_service_kilometer', models.IntegerField(db_column='NEXT_SERVICE_KILOMETER')),
                ('next_service_date', models.DateField(blank=True, db_column='NEXT_SERVICE_DATE', default=datetime.datetime.now)),
                ('note', models.CharField(db_column='NOTE', max_length=256)),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', default=datetime.datetime.now)),
                ('auto_mst_service_item_id', models.ForeignKey(db_column='AUTO_MST_SERVICE_ITEM_ID', on_delete=django.db.models.deletion.RESTRICT, to='automotive.auto_mst_service_item')),
            ],
            options={
                'db_table': 'AUTO_SERVICE_HISTORY',
            },
        ),
        migrations.AddField(
            model_name='auto_mst_service_item',
            name='vehicle_id',
            field=models.ForeignKey(db_column='VEHICLE_ID', on_delete=django.db.models.deletion.RESTRICT, to='automotive.auto_mst_vehicle'),
        ),
    ]
