# Generated by Django 4.1 on 2023-12-10 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0002_auto_mst_service_item_validstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_mst_service_item',
            name='date_created',
            field=models.DateTimeField(blank=True, db_column='DATE_CREATED', default=datetime.datetime.now),
        ),
    ]
