# Generated by Django 4.1 on 2023-12-29 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0003_alter_auto_mst_service_item_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto_mst_service_item',
            name='estimate_price',
        ),
        migrations.RemoveField(
            model_name='auto_mst_service_item',
            name='last_service_date',
        ),
        migrations.RemoveField(
            model_name='auto_mst_service_item',
            name='last_service_kilometer',
        ),
        migrations.RemoveField(
            model_name='auto_service_history',
            name='service_kilometer',
        ),
        migrations.AddField(
            model_name='auto_service_history',
            name='last_service_date',
            field=models.DateField(db_column='LAST_SERVICE_DATE', default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='auto_service_history',
            name='last_service_kilometer',
            field=models.IntegerField(db_column='LAST_SERVICE_KILOMETER', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto_service_history',
            name='validstatus',
            field=models.IntegerField(blank=True, db_column='VALID_STATUS', default=1, null=True),
        ),
    ]
